//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BW.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BW_RoleInPermission
    {
        public int RoleInPermissionId { get; set; }
        public int ModuleId { get; set; }
        public int RoleId { get; set; }
        public bool PAdd { get; set; }
        public bool PEdit { get; set; }
        public bool PDelete { get; set; }
        public bool PView { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual BW_Module BW_Module { get; set; }
        public virtual BW_Role BW_Role { get; set; }
    }
}
