//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BW.Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BW_Role
    {
        public BW_Role()
        {
            this.BW_RoleInPermission = new HashSet<BW_RoleInPermission>();
            this.BW_UserInRole = new HashSet<BW_UserInRole>();
        }
    
        public int RoleId { get; set; }
        public string RoleName { get; set; }
        public string RoleDescription { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<BW_RoleInPermission> BW_RoleInPermission { get; set; }
        public virtual ICollection<BW_UserInRole> BW_UserInRole { get; set; }
    }
}
