//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BW.Repository.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BetterWorkEntities : DbContext
    {
        public BetterWorkEntities()
            : base("name=BetterWorkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BW_Module> BW_Module { get; set; }
        public virtual DbSet<BW_Role> BW_Role { get; set; }
        public virtual DbSet<BW_RoleInPermission> BW_RoleInPermission { get; set; }
        public virtual DbSet<BW_User> BW_User { get; set; }
        public virtual DbSet<BW_UserInRole> BW_UserInRole { get; set; }
    }
}
